###############################################################################
# ██████  ███████ ███████
# ██   ██ ██      ██
# ██████  ███████ ███████
# ██   ██      ██      ██
# ██   ██ ███████ ███████
###############################################################################

domain: #todo
author: #todo
email: #todo
title: "The World Below"


###############################################################################
#  ██████  ██ ████████ ██   ██ ██    ██ ██████
# ██       ██    ██    ██   ██ ██    ██ ██   ██
# ██   ███ ██    ██    ███████ ██    ██ ██████
# ██    ██ ██    ██    ██   ██ ██    ██ ██   ██
#  ██████  ██    ██    ██   ██  ██████  ██████
###############################################################################

repository: facelesspanda/The-World-Below
name: "The World Below"
description: >
  An adventure log with a wiki to the side.
markdown: kramdown


###############################################################################
#      ██ ███████ ██   ██ ██    ██ ██      ██
#      ██ ██      ██  ██   ██  ██  ██      ██
#      ██ █████   █████     ████   ██      ██
# ██   ██ ██      ██  ██     ██    ██      ██
#  █████  ███████ ██   ██    ██    ███████ ███████
###############################################################################

#baseurl: "/The-World-Below/" #check

exclude:
- Gemfile
- Gemfile.lock
- README.md

include:
  #todo

permalink: pretty


###############################################################################
#  ██████  ██████  ██      ██      ███████
# ██      ██    ██ ██      ██      ██
# ██      ██    ██ ██      ██      ███████
# ██      ██    ██ ██      ██           ██
#  ██████  ██████  ███████ ███████ ███████
###############################################################################

collections:
  chronicles:
    output: true
    permalink: /read/:name/
  books:
    output: true
    permalink: /read/:path/
  chapters:
    output: true
    permalink: /read/:path/
  players:
    output: true
  characters:
    output: true
  places:
    output: true
  #todo


###############################################################################
# ██████  ███████ ███████  █████  ██    ██ ██   ████████ ███████
# ██   ██ ██      ██      ██   ██ ██    ██ ██      ██    ██
# ██   ██ █████   █████   ███████ ██    ██ ██      ██    ███████
# ██   ██ ██      ██      ██   ██ ██    ██ ██      ██         ██
# ██████  ███████ ██      ██   ██  ██████  ███████ ██    ███████
###############################################################################

defaults:
  - scope:
      path: ""
      type: "chronicles"
    values:
      layout: "onepager"
      targetcollection: "books"
      bindto: "chronicle"

  - scope:
      path: ""
      type: "books"
    values:
      layout: "onepager"
      targetcollection: "chapters"
      bindto: "book"


###############################################################################
#  ██████  ███████ ███    ███ ███████
# ██       ██      ████  ████ ██
# ██   ███ █████   ██ ████ ██ ███████
# ██    ██ ██      ██  ██  ██      ██
#  ██████  ███████ ██      ██ ███████
###############################################################################

gems:
  ['jekyll-github-metadata']
